### PR TITLE
[BACK-57] Fixed the scrape repo method

### PR DESCRIPTION
**Pull request by 2015builder**
Description of Issue
Fixed the scrapeRepos method for the original 25 repos from the github trending page 

How I implemented
Reformatted the output of the method that receives the 25 trending repos

Other (any extra notes, additional features, problems?,

### CODE REVIEW

**Comment by thomas-woehrle** [comment]
Build fails so try and fix that. Will review maybe tomorrow but currently very busy and this task is not prio1

**Comment by 2015builder** [comment]
> Build fails so try and fix that. Will review maybe tomorrow but currently very busy and this task is not prio1

@thomas-woehrle So the build only fails because the dbUpdater file doesn't work with the new type that I have introduced. So either you change your type in dbUpdater or I have to change my implementatino (but then it would be hard to really solve my issue)

**Comment by thomas-woehrle** [comment]
build is failing @2015builder

**Comment by thomas-woehrle** [comment]
Converted to draft, because I have to commit something to correctly integrate the changes of this branch. Will do that likely today

**Comment by thomas-woehrle** [comment]
Will become a future improvement

**Pull request closed without merging**
