### PR TITLE
[BACK-22] Database setup update

### PR DESCRIPTION
**Pull request by DogukanGun**
Description of Issue

Database setup

How I implemented

I created a general class to use all database operations

### CODE REVIEW

**Review by thomas-woehrle — COMMENTED** [review]
I think we should prefer a functional approach when possible. 

But right now I don't think we will need these classes all together - we can connect to the db in a more flexible way. So leave the PR like this and we can use it or delete it later on.

**Comment by pczern** [comment]
@thomas-woehrle can you specify that please

> I think we should prefer a functional approach when possible.
> 
> But right now I don't think we will need these classes all together - we can connect to the db in a more flexible way. So leave the PR like this and we can use it or delete it later on.

**Comment by pczern** [comment]
@DogukanGun check that you pass tests, this PR will be converted back to Draft in mean time

**Comment by thomas-woehrle** [comment]
> @thomas-woehrle can you specify `more flexible way` please
> 
> > I think we should prefer a functional approach when possible.
> > But right now I don't think we will need these classes all together - we can connect to the db in a more flexible way. So leave the PR like this and we can use it or delete it later on.

I mean connecting to the db where it is needed and not always using the class built in database.ts. 
It is just my way of saying that we don't need this PR.

**Comment by thomas-woehrle** [comment]
Will close for now. We can reopen if needed later on

**Pull request closed without merging**
